export const POST_SECRET_START = 'POST_SECRET_START';
export const POST_SECRET_SUCCESS = 'POST_SECRET_SUCCESS';
export const POST_SECRET_FAILED = 'POST_SECRET_FAILED';

export const FETCH_SECRET_START = 'FETCH_SECRET_START';
export const FETCH_SECRET_SUCCESS = 'FETCH_SECRET_SUCCESS';
export const FETCH_SECRET_FAILED = 'FETCH_SECRET_FAILED';
